### ISSUE TITLE
机器学习周志华电子版是图片格式的扫描版吧？

### ISSUE THREAD

**Issue by IvyGongoogle** [Mikoto10032/DeepLearning#2]
如题，有可以使用查找功能的电子版吗？
谢谢。

**Comment by Mikoto10032** [comment]
> 如题，有可以使用查找功能的电子版吗？
> 谢谢。

抱歉呢，我收集的这些资源都是来自互联网，暂时没有找到周老师的《机器学习》的电子版。这本书作为机器学习入门书籍或者是工具书都是非常合适的，有需要的话建议购买一本😁

**Comment by IvyGongoogle** [comment]
@Mikoto10032  嗯嗯 谢谢了 我已经找到电子版了。
